// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnqcdVf_RCduJQITtNMAh3dHmZ-Eqx2j4',
    appId: '1:175405197111:web:1ed8854a16a6b88dc69cb2',
    messagingSenderId: '175405197111',
    projectId: 'flutter-e273f',
    authDomain: 'flutter-e273f.firebaseapp.com',
    storageBucket: 'flutter-e273f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLmFyxT1RNgYUQj89Zn2V3DL0apj3iwZk',
    appId: '1:175405197111:android:8105037c828b951fc69cb2',
    messagingSenderId: '175405197111',
    projectId: 'flutter-e273f',
    storageBucket: 'flutter-e273f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAApArtUEiAbXc-EwYAgqheHzB8tSSlJmY',
    appId: '1:175405197111:ios:4b55bb20ca061358c69cb2',
    messagingSenderId: '175405197111',
    projectId: 'flutter-e273f',
    storageBucket: 'flutter-e273f.firebasestorage.app',
    iosBundleId: 'com.example.flutternotiffcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAApArtUEiAbXc-EwYAgqheHzB8tSSlJmY',
    appId: '1:175405197111:ios:4b55bb20ca061358c69cb2',
    messagingSenderId: '175405197111',
    projectId: 'flutter-e273f',
    storageBucket: 'flutter-e273f.firebasestorage.app',
    iosBundleId: 'com.example.flutternotiffcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnqcdVf_RCduJQITtNMAh3dHmZ-Eqx2j4',
    appId: '1:175405197111:web:80c29b55880d4f7ac69cb2',
    messagingSenderId: '175405197111',
    projectId: 'flutter-e273f',
    authDomain: 'flutter-e273f.firebaseapp.com',
    storageBucket: 'flutter-e273f.firebasestorage.app',
  );

}